### ISSUE TITLE
no gif support

### ISSUE THREAD

**Issue by Acharab** [vector-im/element-x-android#1529] opened 2023-10-10 20:31 UTC
### Steps to reproduce

1. get a message as a gif 
2. open message
3. message unsupported event

#### What did you expect?
To see a gif
#### What happened instead?
saw the text unsupported event

### Your phone model

Google pixel 7pro

### Operating system version

Android 14

### Application version and app store

0.2.3

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by julioromano** [comment] 2023-10-13 12:13
I can't reproduce, gifs (even animated ones) are showing up when I tried.
Closing this, feel free to reopen if you're still experiencing this (please add more information to reproduce in such case).

**Closed by julioromano** 2023-10-13 12:13 UTC
Labels: T-Defect
