### ISSUE TITLE
Weird formatting in bullet lists with long points

### ISSUE THREAD

**Issue by thefirstofthe300** [vector-im/element-x-android#1090] opened 2023-08-18 10:35 UTC
### Steps to reproduce

Go to this message in the current Element X Play store build: https://matrix.to/#/!QQpfJfZvqxbCfeDgCj:matrix.org/$tVPoJHsPTfA8vjv4xm07y5lPrgwCU7UqOSXLdVsH02s?via=seymour.family&via=matrix.org&via=element.io

#### What did you expect?
Bullet lists to be properly formatted

#### What happened instead?
Bullet lists are cut off before the end of each long point

### Your phone model

Pixel 7

### Operating system version

Android 13

### Application version and app store

EAX Play Store build 0.1.2

### Homeserver

Synapse 1.90 and SS proxy 0.99.5

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment] 2023-08-18 10:41
This might be a duplicate of https://github.com/vector-im/element-x-android/issues/1078.

To add more context, the original message in EW:

<img width="1410" alt="image" src="https://github.com/vector-im/element-x-android/assets/480955/0f39c05c-11d1-4b8b-a777-f6eea293c906">

The current rendering in EAX:

<img width="541" alt="image" src="https://github.com/vector-im/element-x-android/assets/480955/c690b3de-e988-46b0-928f-f1406cabee8e">

It looks like the links got replaced by line breaks somehow.

**Closed** 2023-08-18 13:14 UTC
Labels: S-Major, T-Defect, O-Occasional, A-Timeline
