### ISSUE TITLE
App randomly logs me out after a few mins

### ISSUE THREAD

**Issue by kongo09** [vector-im/element-x-android#1179] opened 2023-08-29 17:32 UTC
### Steps to reproduce

1. Logged into EAX
2. Go somewhere else on my phone
3. Phone goes dark after some inactivity
4. Switch phone on again
5. Open EAX

#### What did you expect?
find myself back where I left

#### What happened instead?
Start screen being logged out. Interestingly, the push notifications are still active in Android including those with decrypted text, which shouldn't be if I'm truly logged out. Clicking on one only takes me to the welcome screen and I need to select the homeserver again and login again.

Trying to login again only requires a new confirmation by MAS, not by upstream keycloak. Sometimes, however, MAS throws an error of `authorization grant not in a pending state`

### Your phone model

Pixel 5

### Operating system version

Android 13

### Homeserver

element.io

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by manuroe** [comment] 2023-08-30 09:02
This is actually a duplicate of https://github.com/vector-im/element-x-android/issues/1153. iOS has actually the same problem. This is either a SDK or backend issue. We are going to investigate it in the SDK first in this [issue](https://github.com/matrix-org/matrix-rust-sdk/issues/2476).

**Closed by manuroe** 2023-08-30 09:02 UTC
Labels: S-Critical, T-Defect, O-Occasional
