### ISSUE TITLE
Unable to leave a room, an error occurred

### ISSUE THREAD

**Issue by ashughes1** [vector-im/element-x-android#765] opened 2023-07-04 11:00 UTC
### Steps to reproduce

1. Long press on a room from the All Chats view
2. Tap on Leave Room
3. Tap on Leave Room again from the confirmation prompt

Alternatively:
1. Open a room from the room list view
2. Tap on the room title
3. Tap on Leave Room
4. Tap on Leave Room again from the confirmation prompt

#### What did you expect?
I should leave the room

#### What happened instead?
A prompt displayed saying "An Error Occurred" and I remained in the room.

#### Details
I was able to leave a room from Element X iOS with the same user logged in without a problem. After leaving the room on iOS, the Android app black-screened after about a minute. It seems I am able to leave previously created rooms that I am already in but any newly created ones that I am invited to display the error.

**Screenshot**
![Screenshot_20230704-115726](https://github.com/vector-im/element-x-android/assets/766595/2115b9a4-93f8-4928-a371-e386baf2ebfe)

#### Rageshakes:
https://github.com/vector-im/element-x-android-rageshakes/issues/157

### Your phone model

Google Pixel 6a

### Operating system version

Android 13

### Application version and app store

Element X 0.1.0-Nightly July 1, 2023

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment] 2023-07-04 13:26
I created a related issue in the Rust SDK repo, since the problem seems to come from there: https://github.com/matrix-org/matrix-rust-sdk/issues/2210

**Comment by csmith** [comment] 2023-07-04 13:27
The error in the logs is: `msg=Can't leave a room that isn't in joined state`.

There's an issue in the rust SDK ([#2078](https://github.com/matrix-org/matrix-rust-sdk/issues/2078)) that results in the wrong membership state being cached, which is what I think is happening here. That would explain why it only affects new rooms - the existing rooms were received and cached with `JOINED` state.

**Comment by jmartinesp** [comment] 2023-07-04 13:28
Then I guess it was just a matter of luck this didn't happen while testing on iOS.

**Comment by jmartinesp** [comment] 2023-07-04 13:32
Maybe our RoomList usage is slightly different than theirs (it's the part of the Rust SDK that loads the room info)...

**Comment by csmith** [comment] 2023-07-04 13:44
I just reproduced it on iOS by:

- Opening EIX
- Receiving an invite to a completely new room from another user
- Accepting the invite
- Going back to the room list
- Trying to leave from the long press menu

Rageshake: https://github.com/vector-im/element-x-ios-rageshakes/issues/554

**Comment by bmarty** [comment] 2023-07-21 15:47
Let's close the issue, feel free to re-open it if you can repro the problem using the latest nightly.

**Closed by bmarty** 2023-07-21 15:47 UTC
Labels: S-Major, T-Defect, O-Occasional, X-Release-Blocker, A-Room, Z-Schedule

**Comment by dillfrescott** [comment] 2024-07-04 00:51
I've got a pixel 8a and I'm getting a ghost room I reinstalled the app and even terminated the room with my home server synapse admin panel. t's weird.

**Comment by dillfrescott** [comment] 2024-07-04 00:59
I've got a pixel 8a and I'm getting a ghost room I reinstalled the app and even terminated the room with my home server synapse admin panel. t's weird.

Edit: it just occured to me that it might be the sliding sync database still storing it
