### ISSUE TITLE
Room list doesn't update with newly joined rooms

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-android#615] opened 2023-06-16 09:28 UTC
### Steps to reproduce

1. Join a room from web (Matrix HQ, in my case)
2. Open EXA

#### What did you expect?
This very active room is top of the room list or can be found using the search

#### What happened instead?
 Do not see the room in the room list and do not see it when filtering the room list

**Comment by bmarty** [comment] 2023-07-17 15:28
Hey @kittykat do you repro with the latest version of the App?

**Comment by kittykat** [comment] 2023-07-17 16:29
@bmarty I can reproduce with latest nightly and Matrix HQ as the room

**Comment by kittykat** [comment] 2023-07-20 15:04
@bmarty Could it be related to vector-im/element-x-ios#1359

**Comment by bmarty** [comment] 2023-07-28 09:46
Yes, it's probably the same thing. Joining a big room can take time, and the sliding sync server still need this time I guess.

**Comment by jonnyandrew** [comment] 2023-08-07 08:55
This issue is marked as 'follow up / candidate for closing' but it sounds like we are fairly confident the issue exists and may affect both platforms. Can I mark as 'triaged'?

**Comment by jmartinesp** [comment] 2023-10-06 10:02
The issue seems to be fixed on iOS, and since the root cause seems to be the same we can probably close this issue too and reopen if we can still reproduce the issue later.

**Closed by jmartinesp** 2023-10-06 10:02 UTC
Labels: S-Critical, T-Defect, O-Occasional, A-Room List, Z-Schedule, X-Maybe-Release-Blocker
