### ISSUE TITLE
UX for signing in with a non-matrix.org homeserver is unnecessarily high friction

### ISSUE THREAD

**Issue by CobaltCause** [vector-im/element-x-android#1051] opened 2023-08-10 22:18 UTC
#### What would you like to do?

Keep the amount of steps it takes to sign in with a matrix.org and non-matrix.org homeserver at parity.

#### Why would you like to do it?

In order to sign in with a matrix.org account, you must:

1. Open the app
2. Tap an emphasized "continue" button
3. Tap an emphasized "continue" button
4. Enter your username and password
5. Tap an emphasized "continue" button

To do the same with a non-matrix.org account, you must:

1. Open the app
2. Tap an emphasized "continue" button
3. Tap a de-emphasized "change account provider" button (diverge)
4. Tap "other"
5. Type in the homeserver address
6. Tap the homeserver address when it shows up in the search results (tapping the submit button on the keyboard is insufficent, you must tap on the search result, which is why this gets its own step)
7. Tap an emphasized "continue" button (converge)
8. Enter your username and password
9. Tap an emphasized "continue" button

That's 4 more (almost twice as many) steps! The use of emphasized and de-emphasized buttons for selecting a non-matrix.org homeserver doesn't feel right for a federated platform either.

#### How would you like to achieve it?

On Element Web/Desktop, I can sign in with a non-matrix.org homeserver in the same amount of steps as the matrix.org homeserver by simply typing my whole MXID into the username field. I think Element X should do the same.

### Have you considered any alternatives?

Leaving it as-is, I guess.

### Are you willing to provide a PR?

No

**Comment by Ruakij** [comment] 2023-08-17 07:53
The design also has some issues that play a role here. Its pretty hard to see the button to change homeserver on dark mode.
Was very confused the app would only support matrix.org because i couldnt see it at all.

I also dont understand the search when using domains or URLs. I had to wait for several seconds for it to notice its a URL so i could click it.

**Comment by bltavares** [comment] 2023-08-19 16:01
Curiously, I've tried to investigate, and it seems that the UI code already take in consideration statues changes on their Preview, but on my device it's barely visible.

I'm not familiar enough with Jetpack's compose Material 3 implementation, but I wonder if the default value [set on the currentColor](https://github.com/vector-im/element-x-android/blob/8ed8b3ebe18b48c066911c39de1701d73d530cf2/libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/theme/components/Button.kt#L255) is not detecting the surface color as it's set to transparent.

<details>
<summary> Screenshots </summary>

| Android Compose Preview | Samsung S23 in Dark Mode on Android 13 |
| --- | --- |
| ![image](https://github.com/vector-im/element-x-android/assets/109474/c481256b-2456-4bd0-876c-e4ebb4eab499) | ![Screenshot_20230819_112932_Element X](https://github.com/vector-im/element-x-android/assets/109474/bfaeca78-ee10-46a2-a310-3524453c3d76) |

</details>

**Comment by axelsimon** [comment] 2023-08-30 11:19
> 6\. Tap the homeserver address when it shows up in the search results (tapping the submit button on the keyboard is insufficent, you must tap on the search result, which is why this gets its own step)

Further to this, the search results for me were entirely hidden from view by / while the on-screen keyboard was up, making it look like the app was doing nothing when i typed the name of my server.

I don't know if it is because the app assumes a screen of at least a certain size (my Pixel 2 has a 1080×1920 screen) or it's more subtle than that: looking at the two screenshots, i realise the search result "element.io" should actually be 2/3 visible even with the keyboard up. In any case, it took me a few seconds to realise the results might be "hidden behind" the keyboard.

Screenshots:
Keyboard visible:
![Screenshot_20230829-122705](https://github.com/vector-im/element-x-android/assets/1172256/4f7d50ea-eb02-4014-b466-5c33bc0fcc6e)

Keyboard hidden by user:
![Screenshot_20230829-122708](https://github.com/vector-im/element-x-android/assets/1172256/ca7f7dad-d75b-4a04-8fde-80e29d50a9cd)

**Comment by kittykat** [comment] 2023-10-24 13:45
I'm going to close this issue as a duplicate of https://github.com/vector-im/element-meta/issues/2133 - we need to align and standardise on the flow between Android and iOS, as iOS currently has a smoother flow with fewer screens

**Closed by kittykat** 2023-10-24 13:45 UTC
Labels: T-Enhancement, A-FTUE, A-Signin
