### ISSUE TITLE
No capitalisation when typing a new message or after a period (.)

### ISSUE THREAD

**Issue by davidegirardi** [vector-im/element-x-android#1408] opened 2023-09-22 06:29 UTC
### Steps to reproduce

1. Type a message
2. Optionally type a period (`.`) and then continue typing

#### What did you expect?
The first letter of the sentence to be upper case.

#### What happened instead?
The letter is lower case.

### Your phone model

Samsung A53

### Operating system version

Android 13

### Application version and app store

0.2.3-nightly (40002030)

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment] 2023-09-27 09:03
This has been fixed in https://github.com/vector-im/element-x-android/pull/988, but when the Rich Text Editor has been integrated, we have this regression. Not sure we can fix in the EXA code. I think it has to be fixed in https://github.com/matrix-org/matrix-rich-text-editor.

@jonnyandrew WDYT?

**Comment by jonnyandrew** [comment] 2023-09-27 09:29
Correct, this will need a change in the library - thanks for raising matrix-org/matrix-rich-text-editor#826

**Comment by fbruetting** [comment] 2023-11-10 21:25
This also happens when RTE is set to being off. If it’s due to RTE, why doesn’t this resolve the issue?

**Comment by jmartinesp** [comment] 2023-11-20 09:39
This was fixed in https://github.com/matrix-org/matrix-rich-text-editor/issues/826, but we still need to release a new version of the library and integrate it in the app.

> This also happens when RTE is set to being off. If it’s due to RTE, why doesn’t this resolve the issue?

This wasn't a problem with the RTE itself, but with the UI component used in the library, which lacked the default flags to allow auto capitalisation.

**Closed** 2023-11-29 15:45 UTC
Labels: S-Minor, T-Defect, O-Frequent, X-Blocked, A-Composer, A-Rich-Text-Editor, Z-Schedule, Z-Polish, Z-Labs
