### ISSUE TITLE
The Rich Text Editor switch doesn't appear to do anything

### ISSUE THREAD

**Issue by K4LCIFER** [vector-im/element-x-android#1535] opened 2023-10-11 05:36 UTC
### Steps to reproduce

1. Enable the rich text editor
2. Observe that there is no rich text editor when you type.

#### What did you expect?

I'd expect to have a rich text editor if the rich text editor is turned on

#### What happened instead?

I don't have a rich text editor

### Your phone model

Google Pixel 6

### Operating system version

Android 14

### Application version and app store

Element X v0.2.3

### Homeserver

matrix.org

### Will you send logs?

yes

### Are you willing to provide a PR?

no

**Comment by julioromano** [comment] 2023-10-11 08:05
I can't reproduce.
If RTE is enabled in the advanced settings, you will see a "Text Formatting" option in the attachments menu (when pressing the "+" button at the left of the composer).

If you see that option it means that the RTE is enabled.

Closing this for now, feel free to reopen if this info doesn't help.

**Closed by julioromano** 2023-10-11 08:05 UTC
Labels: T-Defect
