### ISSUE TITLE
"We couldn't reach this homeserver." - Possible issue with SSO

### ISSUE THREAD

**Issue by Ryonez** [vector-im/element-x-android#954] opened 2023-07-24 13:43 UTC
### Steps to reproduce

After having set up a sliding proxy for my homeserver, I tried connecting to it via Element X on Android. It was able to see the sliding sync proxy, but when attempting to sign in I get the following error:

> We couldn't reach this homeserver. Please check that you have entered the homeserver USL correctly. If the URL is correct, contact your homeserver administrator for further help.

Of note, this homeserver is configured with SSO (Keycloak). SchidiChat desktop has been able to switch over to the sliding proxy.

#### What did you expect?
To be able to sign in.
#### What happened instead?
I wasn't able to.

### Your phone model

Samsung Note 10 +

### Operating system version

Android 12

### Application version and app store

Element X Nightly - 00.1.2-nightly (40001020)

### Homeserver

matrix.alteria.xyz - synapse 1.88.0-docker - sliding-sync v0.99.4-docker

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment] 2023-07-24 13:47
We do not support sign in using SSO. For now only loging using login and password is supported and next step is to support OIDC. Mode details in https://github.com/vector-im/element-meta/issues/1915 (**Authentication**)

**Comment by Ryonez** [comment] 2023-07-24 13:51
Understood.

Might be worth adding an error message that reflects this. And maybe adding that link to the readme, would be good to have a visible feature list there.

**Comment by kittykat** [comment] 2023-10-24 14:28
I'm going to close this issue for now as things are working as intended in that we haven't implemented the feature you're after yet, but it is on the longer term roadmap.

**Closed by kittykat** 2023-10-24 14:28 UTC
Labels: S-Major, T-Defect, O-Occasional, A-Signin
