### ISSUE TITLE
Low hanging improvements to make the rich text editor actions more visually balanced

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-x-android#1321] opened 2023-09-13 18:36 UTC
### Your use case

The active states on formatting options are quite bold. We should find some low hanging tweaks (e.g. reducing icon button sizing, the colour contrast) to see if we can improve it a bit ahead of recording launch materials.

### Are you willing to provide a PR?

No

**Comment by jonnyandrew** [comment] 2023-09-15 10:08
@callumu is this covered already by #1315 ?

**Comment by callumu** [comment] 2023-09-15 10:09
> @callumu is this covered already by #1315 ?

Yes exactly

**Comment by jonnyandrew** [comment] 2023-09-15 11:01
Ok, closing as a duplicate of #1315

**Closed by jonnyandrew** 2023-09-15 11:01 UTC
Labels: T-Enhancement
