### ISSUE TITLE
Keyboard stays after opening another context

### ISSUE THREAD

**Issue by SandResidence** [vector-im/element-x-android#1462] opened 2023-09-29 05:26 UTC
### Steps to reproduce

1. click input to write message
2. click someone's avatar or the room name
3. the keyboard is still visible covering the GUI content

#### What did you expect?
The keyboard to hide

#### What happened instead?
Keyboard persists

### Your phone model

Samsung M52

### Operating system version

LineageOS 20 (build 26.09.2023)

### Application version and app store

Element X 0.2.2

### Homeserver

doesn't mattee

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by SandResidence** [comment] 2023-09-29 05:31
I just installed version 0.2.3 and the problem still exists

**Comment by frebib** [comment] 2023-09-30 13:22
Duplicate of #1375

**Closed** 2023-10-19 13:20 UTC
Labels: S-Tolerable, T-Defect, O-Frequent, A-Composer, A-Navigation
