### ISSUE TITLE
Start a DM takes 15+ seconds

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-android#623] opened 2023-06-16 14:04 UTC
### Steps to reproduce

1. Click the "Start chat" button
2. Search for a user on the "Start chat" screen
3. Click on the right user

#### What did you expect?
See new room quickly

#### What happened instead?
Room takes 10 seconds to appear and has a loading spinner for another 5 seconds after that

### Your phone model

Pixel 6a

### Application version and app store

16th June nightly

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by alfogrillo** [comment] 2023-06-19 10:45
@kittykat do you think EX-iOS is better or are you getting the same performances?

There are performances problems on the Sliding Sync side affecting:

- Creating Room
- Leaving rooms
- Changing state events 

Possibly the issue may be related with the above.

**Comment by kittykat** [comment] 2023-06-19 10:46
@alfogrillo on Friday, I think I was getting better performance on iOS. Maybe @ashughes1 could help confirm that this week?

**Comment by csmith** [comment] 2023-06-23 13:26
I did a quick test and it took about 1-2s to create a DM, with the spinner on the timeline showing for another 1-2s after that. So not super speedy, but not as terrible as 15+ seconds.

 I'll wait to see if @ashughes1 can reproduce and then we can go from there, as I'm wondering if it was just server-side (SS proxy/homeserver) performance that was the problem.

**Comment by csmith** [comment] 2023-06-29 09:35
I think for now we should drop this from the create and join rooms epic, as (a) we can't really action it without logs or reliable reproduction, and (b) it's _probably_ a server-side issue rather than an actual bug client side.

We can keep the issue open for monitoring and see if it reoccurs.

@kittykat @Johennes what do you think?

**Comment by Johennes** [comment] 2023-06-29 10:33
@csmith I think it would be helpful to pin down where the time goes. E.g. if we suspect it's the server, could we underpin that with a network trace? Or if we suspect it's the SDK, are there Android profiling tools we could use to testify that? Once we have that, we can forward the issue to the other teams and remove it from our own epic.

**Comment by csmith** [comment] 2023-06-29 11:48
> I think it would be helpful to pin down where the time goes. E.g. if we suspect it's the server, could we underpin that with a network trace? Or if we suspect it's the SDK, are there Android profiling tools we could use to testify that?

@Johennes definitely, if we can reproduce it... but it doesn't seem like we can at the minute.

I can measure where the couple of seconds are spent, but that won't really inform us which part adds the extra ~10 seconds in the case Kat described seeing.

And while it's for sure worth debugging if it takes 10 seconds, I don't think it's really worth looking in to it taking 1-2 seconds. That feels well within the reasonable range of time for "send a network request, server does complicated things, a different server sends new state to us as a result". If we're not happy with that performance I think we'd be better served by changing to UX to mitigate the impact of the delays (e.g. showing the channel immediately instead of blocking waiting for SS to return).

**Comment by Johennes** [comment] 2023-06-29 12:11
Oh, apologies I hadn't clocked that we couldn't reproduce the original 15+ seconds experience. Agree that it doesn't seem worth our time to dig deeper when it takes 1 to 2 seconds only, especially given that we'll change the whole experience by only creating the room on sending the first message in future.

I'll close this for now.

**Closed by Johennes** 2023-06-29 12:11 UTC
Labels: S-Major, T-Defect, O-Occasional, A-Performance
