### ISSUE TITLE
Message context menu press back twice

### ISSUE THREAD

**Issue by timokoesters** [vector-im/element-x-android#787] opened 2023-07-05 18:16 UTC
### Steps to reproduce

- Long press a message (this also feels too long and has no visual feedback while holding)
- Slide your finger upwards in the menu, the menu will jiggle a bit
- Press back once

#### What did you expect?
Menu will close

#### What happened instead?
Menu slightly moved down to the starting position

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment] 2023-07-06 07:08
I don't think we can override this, it's just the way the component behaves by default and it doesn't allow any customisations of it:

```kotlin
ModalBottomSheetPopup(
        onDismissRequest = {
            if (sheetState.currentValue == Expanded && sheetState.hasPartiallyExpandedState) {
                // This is what is happening
                scope.launch { sheetState.partialExpand() }
            } else { 
                // This is what we'd need
                scope.launch { sheetState.hide() }.invokeOnCompletion { onDismissRequest() }
            }
        },
```

Since the behavior of the bottom sheet is to have a partially expanded state by design, we always end up in the 1st branch of the `if` first, and then the 2nd one if we pressed the back button again.

**Comment by jmartinesp** [comment] 2023-07-19 06:24
I'm closing this, as there's no way to fix this other than Google letting us customise that behaviour in the component in a future release.

**Closed by jmartinesp** 2023-07-19 06:24 UTC
Labels: S-Tolerable, T-Defect, O-Occasional
