### ISSUE TITLE
RTE stops you from typing 166

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-android#1415] opened 2023-09-23 15:54 UTC
### Steps to reproduce

1. type 166, and then space
2. watch the final digit get deleted.

https://github.com/vector-im/element-x-android/assets/1294269/3f72fbd3-c88c-4ac4-b66b-62e243432947

#### What did you expect?

ability to type reliably

#### What happened instead?

pain and chaos

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by libreom** [comment] 2023-09-23 16:03
Redmi 5a Android 11 lineageos 18.1 element x nightly 0.2.3

**Comment by taziden** [comment] 2023-09-25 07:17
Happened to me also (Pixel 4a w/ CalyxOS 4.13.2 / Android 13, element x 0.2.1).
When that happens, there is another bug with the keyboard : first letter is not uppercased.
It doesn't happen all the time, I don't know what triggers the change of behavior.

**Comment by weeman1337** [comment] 2023-09-25 07:18
Also if you type „test 1“ then any char it disappears. For me this is independent of the rich text editor setting.

**Comment by jonnyandrew** [comment] 2023-09-26 10:18
I can't reproduce using either Gboard or SwiftKey. Please can you let me know which soft keyboards you're all using so that I can try to replicate the environment?

**Comment by libreom** [comment] 2023-09-27 08:03
> I can't reproduce using either Gboard or SwiftKey. Please can you let me know which soft keyboards you're all using so that I can try to replicate the environment?

I was using Android Aosp keyboard but same bug also happens on Simple Keyboard.(according to my testing) so you can install https://f-droid.org/packages/rkr.simplekeyboard.inputmethod/
![Screenshot_20230927-133113_Settings.png](https://github.com/vector-im/element-x-android/assets/111110599/2e7e5c1c-9346-408a-8288-d46c17c79e77)

![Screenshot_20230927-133100_Settings.png](https://github.com/vector-im/element-x-android/assets/111110599/5ffc403a-6c53-4d51-bc36-691c54e629ea)

**Comment by jonnyandrew** [comment] 2023-09-27 08:24
Thanks for the info @libreom, I am now able to reproduce by switching to Simple Keyboard.

**Comment by dasJ** [comment] 2023-10-02 08:02
Something that is probably related (I assume the wrong hints are given to the keyboard?): Swiftkey doesn't remove the whitespace before "?", so my messages end up as "Does this work ?" rather than "Does this work?"

**Comment by Ao1Pointblank** [comment] 2023-10-07 13:55
Happens with OpenBoard on GrapheneOS as well. 
I also tested with the default Graphene keyboard but I think that is just AOSP keyboard which is already mentioned in this thread by another user. I reiterate, this bug only occurs in Element X, not regular Element or any other apps.

**Comment by Ao1Pointblank** [comment] 2023-10-07 14:06
Happens with OpenBoard on GrapheneOS as well. 
I also tested with the default Graphene keyboard but I think that is just AOSP keyboard which is already mentioned in this thread by another user. I reiterate, this bug only occurs in Element X, not regular Element or any other apps. 

Floris Board beta and stable are both immune to this bug, probably because Floris has no autocorrect.

**Comment by Hywan** [comment] 2023-11-06 09:44
How can we help to solve this bug? It's pretty annoying… :-).

**Comment by jonnyandrew** [comment] 2023-11-06 10:23
> How can we help to solve this bug? It's pretty annoying… :-).

I've looked into this once but didn't have time to get to the bottom of it. I've attached a few notes to the RTE issue in case anybody wanted to help progress things! https://github.com/matrix-org/matrix-rich-text-editor/issues/844#issuecomment-1794500744

**Comment by jmartinesp** [comment] 2023-11-20 11:35
This issue was fixed in https://github.com/matrix-org/matrix-rich-text-editor/pull/878, but we still need to integrate it into the app.

**Closed** 2023-11-20 11:35 UTC
Labels: S-Major, T-Defect, O-Occasional, Team: Element X Feature, A-Rich-Text-Editor, Z-Schedule, Z-Labs
